title: Wikipedia Bot
subtitle: A bot that tweets random Wikipedia articles daily
cover: na
preview type: embed
preview: <a class="twitter-timeline" data-height="700" data-width="500" data-dnt="true" data-theme="dark" href="https://twitter.com/DailyRandomWik1?ref_src=twsrc%5Etfw">Tweets by DailyRandomWik1</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>