title: Untitled Duck Game
subtitle: Unity platformer
cover: na
preview type: embed
preview: <iframe frameborder="0" src="https://itch.io/embed-upload/8640012?color=e94af6" allowfullscreen="" width="960" height="665"><a href="https://turtleship.itch.io/untitled-duck-game">Play Untitled Duck Game on itch.io</a></iframe>