title: Maza Game
subtitle: Yes i just mispelt that title and stuck with it
cover: na
preview type: embed
preview: '<iframe src="https://nathanmachane.repl.co/MazaGame" style="border:0px #ffffff none;" name="myiFrame" scrolling="no" frameborder="1" marginheight="0px" marginwidth="0px" height="600px" width="960px" allowfullscreen></iframe>'