title: Maza Game
subtitle: Yes i just mispelt that title and stuck with it
cover: na
preview type: embed
preview: <iframe frameborder="0" src="https://itch.io/embed-upload/7221119?color=333333" allowfullscreen="" width="960" height="600"><a href="https://turtleship.itch.io/maza-game">Play Maza Game on itch.io</a></iframe>